name: Build and Publish Helm Chart
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Package Helm Chart
        run: helm package . -d ./charts

      - name: Index Helm Chart
        run: helm repo index ./charts

      - name: registry login
        run: helm registry login ghcr.io --username michaelkoch --password ${{secrets.GITHUB_TOKEN  }}

      - name: helm push
        run: helm push ./charts/*.tgz oci://ghcr.io/michaelkoch 
